import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import SideHeader from "./invoice/(components)/side-header";
export const metadata: Metadata = {
  title: "Invoice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-4 h-screen">
          <div className="">
          <SideHeader />
          </div>
          <div className="w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
